Tomas' solutions for #22
FbW36/22-PB-conditionals-pt1 pull request #11
Opened 2020-10-26 14:20 UTC by TomasEliz

2020-10-27 10:37 UTC, ciamac-da requested changes

2020-10-27 10:37 UTC, ciamac-da commented on tomas/index.js
> +if((x < 50 || x > 99) && (y < 50 || y > 99)) {
Your integer variable are in range of  < 49.999 or bigger than 99! It should be in range of 50 to 99!!
You also have to check if EITHER of them are in the range not both of them!

2020-10-27 10:37 UTC, ciamac-da commented on tomas/index.js
> +if((x3 != 15 && y3 != 15) || (x3 + y3 == 15)) {
You have to check if x3 or y3 are 15

2020-10-27 10:37 UTC, ciamac-da commented on tomas/index.js
> +let z2 = 22;
The result is correct but make sure that you use Math.abs() method to calculate the difference.

2020-10-27 11:58 UTC, TomasEliz commented
I see. Well I guess I understood it the wrong way. I thought EITHER OF =
NONE OF.  And that's what I checked. I got confused thinking that maybe if
you'd want me to check if x or y is part of some group, the exercise would
state "CHECK IF ONE OF THOSE" is that and that.

On Tue, 27 Oct 2020 at 11:38, cia-from-earth <notifications@github.com>
wrote:

> *@ciamac-da* requested changes on this pull request.
> ------------------------------
>
> In tomas/index.js
> <https://github.com/FbW36/22-PB-conditionals-pt1/pull/11#discussion_r512576073>
> :
>
> > @@ -0,0 +1,84 @@
> +let log = console.log;
> +
> +// Check if two given integer values are in the range 50 to 99 (this includes both 50 and 99). Print true if either of them are in the range
> +let x = 1;
> +let y = 100;
> +let result;
> +if((x < 50 || x > 99) && (y < 50 || y > 99)) {
>
> Your integer variable are in range of < 49.999 or bigger than 99! It
> should be in range of 50 to 99!!
> You also have to check if EITHER of them are in the range not both of them!
> ------------------------------
>
> In tomas/index.js
> <https://github.com/FbW36/22-PB-conditionals-pt1/pull/11#discussion_r512578537>
> :
>
> > +}
> +else {
> +    log(80);
> +}
> +
> +// Check whether the sum of two integers is 8, or whether their difference is 8. If one of these is the case, print true
> +let x2 = 5;
> +let y2 = 3;
> +if((x2 + y2) == 8 || (x2 - y2) == 8) {
> +    log('6 -->', true);
> +}
> +
> +// Check whether either one of two integers is 15, or if their sum is 15. If one of these is the case, print true
> +let x3 = 7;
> +let y3 = 8;
> +if((x3 != 15 && y3 != 15) || (x3 + y3 == 15)) {
>
> You have to check if x3 or y3 are 15
> ------------------------------
>
> In tomas/index.js
> <https://github.com/FbW36/22-PB-conditionals-pt1/pull/11#discussion_r512579884>
> :
>
> > +let x4 = 49;
> +let y4 = 16;
> +if((x4 % 7 === 0) || (x4 % 11 === 0) || (y4 % 7 === 0) || (y4 % 11 === 0)) {
> +    log('8 -->', true);
> +}
> +
> +// Calculate the sum of the two given integers. If the two values are the same, then print triple their sum
> +let x5 = 3;
> +let y5 = 3;
> +let sum = x5 + y5;
> +if(x5 === y5) {
> +    log('triple sum =', sum * 3);
> +}
> +
> +// Calculate the difference between a specified number and 19. Print double the difference if the specified number is greater than 19
> +let z2 = 22;
>
> The result is correct but make sure that you use Math.abs() method to
> calculate the difference.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FbW36/22-PB-conditionals-pt1/pull/11#pullrequestreview-517552747>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQGNSCYDA7LN5Y56TVL3ZXLSM2PIXANCNFSM4S7OFYHQ>
> .
>

2020-11-01 17:45 UTC, ciamac-da approved these changes

2020-11-01 17:46 UTC, merged